export const FETCH_MENUS = "FETCH_MENUS";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_HISTORY = "FETCH_HISTORY";
export const ADD_ORDER = "ADD_ORDER";
export const CHANGE_AMOUNT_ORDER = "CHANGE_AMOUNT_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";
export const HANDLE_BAYAR = "HANDLE_BAYAR";